<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512">
<title></title>
<g id="icomoon-envelope">
</g>
<path fill="#000" d="M479.999 64h-447.999c-17.671 0-32 14.312-32 32v320c0 17.688 14.329 32 32 32h447.999c17.672 0 32.001-14.312 32.001-32v-320c0-17.688-14.329-32-32.001-32zM416 128l-160 128-160-128h320zM448 384h-384v-224l192 160 192-160v224z"></path>
</svg>
